language: cpp

compiler:
  - g++
  - clang

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

before_install:
  - git submodule update --init --recursive
  - sudo apt-get -qq update
  - sudo apt-get -qq remove gcc gcc-4.6
  - sudo apt-get -qq install gcc-4.7

install:
  - cmake -Hprojects/CMake -BBuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cd Build
  - make
  - cd ..

script:
  - cd Build
  - ctest -V
